version: "3.8"

services:
  ddnet-server:
    image: ddnet-server
    container_name: ddnet-server
    volumes:
      - data:/ddnet-server/data
    ports:
      - 8303:8303/udp
    restart: unless-stopped

volumes:
  data:
